$(function(){
  $('#add_address').click(function(){
    var index = layer.open({
      type: 1,
      title: 0,
      area: '700px',
      closeBtn: 0,
      shadeClose: true,
      content:  '<div class="order-pay-address">'
                + '<div class="line">'
                +    '<div class="left">'
                +      '<span class="a-t">新增收货地址</span>'
                +    '</div>'
                +    '<div class="right lh-30">'
                +      '<span class="form-need">*</span>均为必须项'
                +    '</div>'
                +  '</div>'
                +  '<div class="line">'
                +    '<div class="left">'
                +      '所在区域<span class="form-need">*</span>'
                +    '</div>'
                +    '<div class="right">'
                +      '<div class="p-dropdown mr-10">'
                +          '<label type="checkbox">'
                +              '<span>*省</span>'
                +              '<i></i>'
                +              '<input type="checkbox" name="dd_province" value="">'
                +              '<ul></ul>'
                +          '</label>'
                +      '</div>'
                +      '<div class="c-dropdown mr-10">'
                +          '<label type="checkbox">'
                +              '<span>*市</span>'
                +              '<i></i>'
                +              '<input type="checkbox" name="dd_city" value="">'
                +              '<ul></ul>'
                +          '</label>'
                +      '</div>'
                +      '<div class="a-dropdown mr-10">'
                +          '<label type="checkbox">'
                +              '<span>*县</span>'
                +              '<i></i>'
                +              '<input type="checkbox" name="dd_area" value="">'
                +              '<ul></ul>'
                +          '</label>'
                +      '</div>'
                +    '</div>'
                +  '</div>'
                +  '<div class="line">'
                +    '<div class="left">'
                +      '详细地址<span class="form-need">*</span>'
                +    '</div>'
                +    '<div class="right">'
                +      '<textarea name="name" placeholder="建议您如实填写详细收货地址, 例如街道名称、门牌号码、楼层和房间号等信息" rows="5" cols="66"></textarea>'
                +    '</div>'
                +  '</div>'
                +  '<div class="line">'
                +    '<div class="left">'
                +      '收货人姓名<span class="form-need">*</span>'
                +    '</div>'
                +    '<div class="right">'
                +      '<input type="text" name="name" maxlength="12"  placeholder="不超过12个字" value="">'
                +    '</div>'
                +  '</div>'
                +  '<div class="line">'
                +    '<div class="left">'
                +      '手机号码 <span class="form-need">*</span>'
                +    '</div>'
                +    '<div class="right">'
                +      '<input type="text" name="phone" placeholder="电话号码、手机号码必须填一项" value="">'
                +    '</div>'
                +  '</div>'
                +  '<div class="line">'
                +    '<div class="left">&nbsp;</div>'
                +    '<div class="right">'
                +      '<div class="m-checkbox">'
                +          '<label type="checkbox">'
                +              '<input type="checkbox" name="agreement"  checked>'
                +              '<i></i>'
                +              '设置为默认地址'
                +          '</label>'
                +      '</div>'
                +    '</div>'
                +  '</div>'
                +  '<div class="line">'
                +    '<div class="left">&nbsp;</div>'
                +    '<div class="right">'
                +      '<button type="button" id="save" name="button">保存</button>'
                +    '</div>'
                +  '</div>'
                + '</div>'
      });
      //保存新增地址
      $('#save').click(function(){

      });
  });
});
