<?php
$RouteArr=array(
    //'控制器小写@方法小写'=>'真实控制器名@真实方法名'
    'debt@test'=>'Debt@Test',
    //债务催收
    'debt@index'=>'Debt@Index',
    'debt@debtlists'=>'Debt@DebtLists',
    'debt@debtdetails'=>'Debt@DebtDetails',
    'debt@publish'=>'Debt@DebtPublish',
    //线索悬赏
    'reword@index'=>'Reword@Index',
    'reword@publish'=>'Reword@RewordPublish',
    //资产转让
    'asset@publish'=>'Asset@Publish',
    'asset@lists'=>'Asset@Lists',
    'asset@details'=>'Asset@Details',
    'asset@order'=>'Asset@Order',
    'asset@choicepay'=>'Asset@ChoicePay',
    'asset@pay'=>'Asset@Pay',

    //寻找处置方
    'find@choicefind'=>'Find@ChoiceFind',
    'find@team'=>'Find@Team',
    //搜索老赖
    'deadbeat@index'=>'DeadBeat@Index',
    //会员中心
    'member@login'=>'Member@Login',
    'member@signout'=>'Member@SignOut',
    'member@register'=>'Member@Register',
    'member@registertwo'=>'Member@RegisterTwo',
    'member@registerthree'=>'Member@RegisterThree',
    'member@findpasswd'=>'Member@FindPasswd',
    'member@changemobile'=>'Member@ChangeMobile',
    'member@editpassword'=>'Member@EditPassWord',
    'member@systemmessage'=>'Member@SystemMessage',
    'member@advice'=>'Member@Advice',
    'member@center'=>'Member@Center',
    'member@assetlist'=>'Member@AssetList',
    'member@sellorderlist'=>'Member@SellOrderList',
    'member@buyorderlist'=>'Member@BuyOrderList',
    'member@buyorderdetail'=>'Member@BuyOrderDetail',
    //普通会员中心
    'memberperson@index'=>'MemberPerson@Index',
    'memberperson@editinfo'=>'MemberPerson@EditInfo',
    'memberperson@applydebtorder'=>'MemberPerson@ApplyDebtOrder',
    'memberperson@bondlist'=>'MemberPerson@BondList',
    'memberperson@debtlist'=>'MemberPerson@DebtList',
    'memberperson@rewordlist'=>'MemberPerson@RewordList',
    'memberperson@findteam'=>'MemberPerson@FindTeam',
    'memberperson@focusdebtlist'=>'MemberPerson@FocusDebtList',
    //律师会员中心
    'memberlawyer@index'=>'MemberLawyer@Index',
    'memberlawyer@editinfo'=>'MemberLawyer@EditInfo',
    'memberlawyer@applydebtorder'=>'MemberLawyer@ApplyDebtOrder',
    'memberlawyer@creditorder'=>'MemberLawyer@CreditOrder',
    'MemberLawyer@demandlist'=>'MemberLawyer@DemandList',
    'memberlawyer@demanddetails'=>'MemberLawyer@DemandDetails',
    'memberlawyer@setdemand'=>'MemberLawyer@SetDemand',
    //催收公司会员中心
    'memberfirm@index'=>'MemberFirm@Index',
    'memberfirm@editinfo'=>'MemberFirm@EditInfo',
    'memberfirm@applydebtorder'=>'MemberFirm@ApplyDebtOrder',
    'memberfirm@creditorder'=>'MemberFirm@CreditOrder',
    'memberfirm@demandlist'=>'MemberFirm@DemandList',
    'memberfirm@demanddetails'=>'MemberFirm@DemandDetails',
    'memberfirm@setdemand'=>'MemberFirm@SetDemand',
    //订单支付
    'pay@alipay'=>'Pay@AliPay',
    'pay@alipaynotify'=>'Pay@AliPayNotify',
    'pay@result'=>'Pay@Result',

);
